[workspace]
resolver = "2"

members = [
	"piltover",
	"bins/bindgen",
]

[workspace.dependencies]
cainome = { version = "0.5.0", features = ["abigen-rs"] }
starknet = "0.12"
piltover = { path = "piltover" }
