[workspace]
resolver = "2"

members = [
	"piltover",
	"bins/bindgen",
]

[workspace.dependencies]
cainome = { version = "0.6.0", features = ["abigen-rs"] }
starknet = "0.14.0"
piltover = { path = "piltover" }
