[package]
name = "piltover"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.13.1"
openzeppelin = "0.20.0"
integrity = "2.0.0"

[dev-dependencies]
starknet = "2.13.1"
snforge_std = "0.52.0"
# openzeppelin_testing = "0.20.0"

[scripts]
test = "snforge test"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
casm = true
sierra = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.fmt]
sort-module-level-items = true

[features]
messaging_test = []
